---
- name: Install and configure MariaDB with Python3 and pip
  hosts: aws
  vars:
    mysql_root_password: "1234" # root 계정 비밀번호
  become: yes  # sudo 권한으로 실행

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install required packages (MariaDB, Python3, pip)
      apt:
        name:
          - mariadb-server
          - python3
          - python3-pip
          - python3-mysqldb  # MySQL-Python 라이브러리 (Ansible mysql_user 모듈 필요)
        state: present

    - name: Start and enable MariaDB service
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Ensure MariaDB root password is set
      mysql_user:
        name: root
        host: localhost
        password: "{{ mysql_root_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        plugin: mysql_native_password
        state: present
        update_password: always
      ignore_errors: yes  # 초기 설정 오류 방지

    - name: Create .my.cnf for Ansible root access
      copy:
        dest: /root/.my.cnf
        content: |
          [client]
          user=root
          password= "{{ mysql_root_password }}"
        owner: root
        group: root
        mode: '0600'

    - name: Restart MariaDB service after password change
      service:
        name: mariadb
        state: restarted

    - name: Ensure root can login from any host
      mysql_user:
        name: root
        host: '%'
        password: "{{ mysql_root_password }}"
        priv: "*.*:ALL,GRANT"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        state: present

    - name: Flush privileges to apply changes
      mysql_query:
        query: "FLUSH PRIVILEGES;"
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Change bind-address to allow remote connections
      lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
      notify:
        - Restart MariaDB

    - name: Ensure MySQL database exists
      mysql_db:
        name: my_database
        state: present

#    방화벽 오픈 필요시 # 제거
#    - name: Allow MySQL port through UFW (fixed)
#      ufw:
#        rule: allow
#        port: '3306'
#        proto: tcp

  handlers:
    - name: Restart MariaDB
      service:
        name: mariadb
        state: restarted
