---
- name: Mount Samba share on client
  hosts: u22c  # 클라이언트 서버
  become: yes  # 관리자 권한으로 실행
  vars:
    samba_server: "192.168.20.1"  # Samba 서버 호스트 이름 또는 IP 주소
    samba_share: "humans"  # 공유 디렉터리 이름
    mount_point: "/dir2"  # 클라이언트에서 마운트할 디렉터리
    samba_user: "user1"  # Samba 사용자
    samba_password: "123456"  # Samba 비밀번호

  tasks:
    - name: Install cifs-utils package (for mounting CIFS shares)
      apt:
        name: cifs-utils
        state: present
        update_cache: yes

    - name: Create mount point directory
      file:
        path: "{{ mount_point }}"
        state: directory
        mode: '0755'

    - name: Mount the Samba share
      mount:
        path: "{{ mount_point }}"
        src: "//{{ samba_server }}/{{ samba_share }}"
        fstype: cifs
        opts: "username={{ samba_user }},password={{ samba_password }},iocharset=utf8,vers=3.0"
        state: mounted
        dump: 0
        passno: 0

    - name: Verify the mount
      command: mount | grep "{{ mount_point }}"
      register: mount_output
      changed_when: false

    - name: Show mount details
      debug:
        msg: "{{ mount_output.stdout }}"
